name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      DOCKER_IMAGE_REPOSITORY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image tag
        id: docker-image
        run: |
          echo "tag=${{ inputs.environment }}/${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.docker-image.outputs.tag }}
          build-args: |
            ENV_TAG=${{ inputs.environment }}