name: Push Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [9.x]
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup
        run: |
          pnpm install --frozen-lockfile --prefer-frozen-lockfile --ignore-scripts
          pnpm audit --audit-level=critical

      - name: Lint
        run: pnpm run lint

      - name: Type checking
        run: npm run type-check

      - name: Run Unit Test
        run: pnpm test -- --ci --coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: pnpm run build

      # - name: Install Playwright (used for Storybook and E2E tests)
      #   run: npx playwright install --with-deps

      # - name: Run storybook tests
      #   run: npm run test-storybook:ci

      # - name: Run E2E tests
      #   run: npx percy exec -- npm run test:e2e
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      #     CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7